### ISSUE TITLE
Lab3-4 Замечания

### ISSUE THREAD

**Issue by Andrewbooq** [NuraMun/pp3#1]
1 Makefile куда-то потерялся. Наверно не проверяла под Linux?
![image](https://github.com/user-attachments/assets/2bc6c48b-a061-445d-a099-66b2544c7b6f)
В ThreadPool.h есть #include <Windows.h> без условной компиляции. Думаю просто забыла убрать

2 Это условие не корректно, должен быть логический оператор `||` между `defined(_WIN32)  defined(_WIN64)` там где #include <Windows.h> и еще где-то, просмотри все условия.
![image](https://github.com/user-attachments/assets/31ab621b-a0eb-4095-bbfe-412afeffd5c5)
Ну и смотри, там еще 2 ворнинга:
- с конверсией типов из дробного в целое `long long fn = (round)(f / 10000.0);`. Тут тогда явное преобразование надо static_cast.....
- не используешь `unsigned int threadID;`, надо либо ее получать из поледнего параметра _beginthreadex и выводить для информации, либо вообще убрать, если не нужно.

3 Под linux не собирается. Ты переимновала файлы ThreadsPools в ThreadPool (S), а сласс остался ThreadsPool, но кое-где по коду ты потеряла S,
```
 pthread_create(&thread, nullptr, [](void* param) -> void* {
            static_cast<ThreadPool*>(param)->run();
            return nullptr;
            }, this);
```
ну  threads.push_back(reinterpret_cast<HANDLE>(thread));, конечно в линуксе неизвестный тип HANDLE

![image](https://github.com/user-attachments/assets/b96d1604-b9e5-4350-be7f-ea21552f5487)

Итог: Принципиально всё правильно, под Linux убери ошибки сборки. Присылай подправленный вариант и жду на зачете 19.12.

**Comment by NuraMun** [comment]
Добрый вечер, сейчас все запускается под Linux, исправила ошибки.

**Comment by Andrewbooq** [comment]
All is good.
